### PR TITLE
Fix UI issue

### PR DESCRIPTION
**Pull request by raman325**
## Type of change

-   [ ] Dependency upgrade
-   [x] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (which adds functionality)
-   [ ] Breaking change (fix/feature causing existing functionality to break)
-   [ ] Code quality improvements to existing code or addition of tests

## Additional information

-   This PR fixes or closes issue: fixes #
-   This PR is related to issue:

### CODE REVIEW

**Comment by raman325** [comment]
@tykeal  do you mind testing this PR? Trying to figure out where the issue is, and as far as I can tell it's a timing issue but I can't quite be sure

**Comment by tykeal** [comment]
I'll give it a try in the morning. I'm nowhere near my test system right now

**Comment by tykeal** [comment]
@raman325  Well, it loads, unlike what I was seeing with 0.4.0. Everything is showing as unavailable though. I removed the configuration, added it back in and then when to look at the dashboard and everything was showing as available when I first got to it but shortly after it showed everything as unavailable again.

**Comment by tykeal** [comment]
I enabled debug for the component and here's all the spew for my test system related to LCM

```
2024-03-22 06:09:49.318 DEBUG (MainThread) [custom_components.lock_code_manager] Exposed strategy module at /lock_code_manager_files/lock-code-manager-strategy.js
2024-03-22 06:09:49.318 DEBUG (MainThread) [custom_components.lock_code_manager] Strategy module already registered with resource ID 4102097731c84b69898804e97e5fccee
2024-03-22 06:09:49.318 DEBUG (MainThread) [custom_components.lock_code_manager] Finished setting up websocket API
2024-03-22 06:09:49.332 INFO (MainThread) [custom_components.lock_code_manager] 73bd631cc6ba05c96f7aec7ec67a2177 (Foo): Creating and/or updating entities
2024-03-22 06:09:49.354 DEBUG (MainThread) [custom_components.lock_code_manager] 73bd631cc6ba05c96f7aec7ec67a2177 (Foo): Adding following locks: ['lock.test_lock']
2024-03-22 06:09:49.354 DEBUG (MainThread) [custom_components.lock_code_manager.helpers] 73bd631cc6ba05c96f7aec7ec67a2177 (Foo): Created lock instance ZWaveJSLock(domain=zwave_js, lock=lock.test_lock)
2024-03-22 06:09:49.354 DEBUG (MainThread) [custom_components.lock_code_manager] 73bd631cc6ba05c96f7aec7ec67a2177 (Foo): Creating lock instance for lock ZWaveJSLock(domain=zwave_js, lock=lock.test_lock)
2024-03-22 06:09:49.354 DEBUG (MainThread) [custom_components.lock_code_manager] 73bd631cc6ba05c96f7aec7ec67a2177 (Foo): Creating coordinator for lock ZWaveJSLock(domain=zwave_js, lock=lock.test_lock)
2024-03-22 06:09:49.355 DEBUG (MainThread) [custom_components.lock_code_manager.coordinator] Finished fetching lock_code_manager lock.test_lock data in 0.000 seconds (success: True)
2024-03-22 06:09:49.355 DEBUG (MainThread) [custom_components.lock_code_manager] 73bd631cc6ba05c96f7aec7ec67a2177 (Foo): Adding lock lock.test_lock slot 1 sensor and event entity
2024-03-22 06:09:49.355 DEBUG (MainThread) [custom_components.lock_code_manager.entity] 73bd631cc6ba05c96f7aec7ec67a2177 (Foo): Adding entity sensor.test_lock_code_slot_1
2024-03-22 06:09:49.356 DEBUG (MainThread) [custom_components.lock_code_manager] 73bd631cc6ba05c96f7aec7ec67a2177 (Foo): Adding lock lock.test_lock slot 2 sensor and event entity
2024-03-22 06:09:49.356 DEBUG (MainThread) [custom_components.lock_code_manager.entity] 73bd631cc6ba05c96f7aec7ec67a2177 (Foo): Adding entity binary_sensor.test_lock_code_slot_2_in_sync
2024-03-22 06:09:49.356 DEBUG (MainThread) [custom_components.lock_code_manager.entity] 73bd631cc6ba05c96f7aec7ec67a2177 (Foo): Adding entity sensor.test_lock_code_slot_2
2024-03-22 06:09:49.357 DEBUG (MainThread) [custom_components.lock_code_manager] 73bd631cc6ba05c96f7aec7ec67a2177 (Foo): Adding lock lock.test_lock slot 3 sensor and event entity
2024-03-22 06:09:49.357 DEBUG (MainThread) [custom_components.lock_code_manager.entity] 73bd631cc6ba05c96f7aec7ec67a2177 (Foo): Adding entity binary_sensor.test_lock_code_slot_3_in_sync
2024-03-22 06:09:49.358 DEBUG (MainThread) [custom_components.lock_code_manager.entity] 73bd631cc6ba05c96f7aec7ec67a2177 (Foo): Adding entity sensor.test_lock_code_slot_3
2024-03-22 06:09:49.358 DEBUG (MainThread) [custom_components.lock_code_manager] 73bd631cc6ba05c96f7aec7ec67a2177 (Foo): Adding PIN enabled binary sensor for slot 1
2024-03-22 06:09:49.358 DEBUG (MainThread) [custom_components.lock_code_manager.entity] 73bd631cc6ba05c96f7aec7ec67a2177 (Foo): Adding entity binary_sensor.foo_code_slot_1_active
2024-03-22 06:09:49.359 DEBUG (MainThread) [custom_components.lock_code_manager.entity] 73bd631cc6ba05c96f7aec7ec67a2177 (Foo): Adding entity event.foo_code_slot_1
2024-03-22 06:09:49.359 DEBUG (MainThread) [custom_components.lock_code_manager.entity] 73bd631cc6ba05c96f7aec7ec67a2177 (Foo): Adding entity text.foo_code_slot_1_name
2024-03-22 06:09:49.361 DEBUG (MainThread) [custom_components.lock_code_manager.entity] 73bd631cc6ba05c96f7aec7ec67a2177 (Foo): Adding entity text.foo_code_slot_1_pin
2024-03-22 06:09:49.361 DEBUG (MainThread) [custom_components.lock_code_manager.entity] 73bd631cc6ba05c96f7aec7ec67a2177 (Foo): Adding entity switch.foo_code_slot_1_enabled
2024-03-22 06:09:49.361 DEBUG (MainThread) [custom_components.lock_code_manager.entity] 73bd631cc6ba05c96f7aec7ec67a2177 (Foo): Sending signal from switch.foo_code_slot_1_enabled to binary sensor that slot 1 is ready
2024-03-22 06:09:49.361 DEBUG (MainThread) [custom_components.lock_code_manager] 73bd631cc6ba05c96f7aec7ec67a2177 (Foo): Adding enabled entity for slot 1
2024-03-22 06:09:49.361 DEBUG (MainThread) [custom_components.lock_code_manager] 73bd631cc6ba05c96f7aec7ec67a2177 (Foo): Adding name entity for slot 1
2024-03-22 06:09:49.361 DEBUG (MainThread) [custom_components.lock_code_manager] 73bd631cc6ba05c96f7aec7ec67a2177 (Foo): Adding pin entity for slot 1
2024-03-22 06:09:49.362 DEBUG (MainThread) [custom_components.lock_code_manager] 73bd631cc6ba05c96f7aec7ec67a2177 (Foo): Adding pin_used entity for slot 1
2024-03-22 06:09:49.362 DEBUG (MainThread) [custom_components.lock_code_manager] 73bd631cc6ba05c96f7aec7ec67a2177 (Foo): Adding PIN enabled binary sensor for slot 2
2024-03-22 06:09:49.362 DEBUG (MainThread) [custom_components.lock_code_manager.entity] 73bd631cc6ba05c96f7aec7ec67a2177 (Foo): Adding entity binary_sensor.foo_code_slot_2_active
2024-03-22 06:09:49.362 DEBUG (MainThread) [custom_components.lock_code_manager.entity] 73bd631cc6ba05c96f7aec7ec67a2177 (Foo): Adding entity event.foo_code_slot_2
2024-03-22 06:09:49.363 DEBUG (MainThread) [custom_components.lock_code_manager.entity] 73bd631cc6ba05c96f7aec7ec67a2177 (Foo): Adding entity text.foo_code_slot_2_name
2024-03-22 06:09:49.363 DEBUG (MainThread) [custom_components.lock_code_manager.entity] 73bd631cc6ba05c96f7aec7ec67a2177 (Foo): Adding entity text.foo_code_slot_2_pin
2024-03-22 06:09:49.364 DEBUG (MainThread) [custom_components.lock_code_manager.entity] 73bd631cc6ba05c96f7aec7ec67a2177 (Foo): Adding entity switch.foo_code_slot_2_enabled
2024-03-22 06:09:49.364 DEBUG (MainThread) [custom_components.lock_code_manager.entity] 73bd631cc6ba05c96f7aec7ec67a2177 (Foo): Sending signal from switch.foo_code_slot_2_enabled to binary sensor that slot 2 is ready
2024-03-22 06:09:49.364 DEBUG (MainThread) [custom_components.lock_code_manager] 73bd631cc6ba05c96f7aec7ec67a2177 (Foo): Adding enabled entity for slot 2
2024-03-22 06:09:49.364 DEBUG (MainThread) [custom_components.lock_code_manager] 73bd631cc6ba05c96f7aec7ec67a2177 (Foo): Adding name entity for slot 2
2024-03-22 06:09:49.364 DEBUG (MainThread) [custom_components.lock_code_manager] 73bd631cc6ba05c96f7aec7ec67a2177 (Foo): Adding pin entity for slot 2
2024-03-22 06:09:49.364 DEBUG (MainThread) [custom_components.lock_code_manager] 73bd631cc6ba05c96f7aec7ec67a2177 (Foo): Adding pin_used entity for slot 2
2024-03-22 06:09:49.364 DEBUG (MainThread) [custom_components.lock_code_manager] 73bd631cc6ba05c96f7aec7ec67a2177 (Foo): Adding PIN enabled binary sensor for slot 3
2024-03-22 06:09:49.364 DEBUG (MainThread) [custom_components.lock_code_manager.entity] 73bd631cc6ba05c96f7aec7ec67a2177 (Foo): Adding entity binary_sensor.foo_code_slot_3_active
2024-03-22 06:09:49.365 DEBUG (MainThread) [custom_components.lock_code_manager.entity] 73bd631cc6ba05c96f7aec7ec67a2177 (Foo): Adding entity event.foo_code_slot_3
2024-03-22 06:09:49.365 DEBUG (MainThread) [custom_components.lock_code_manager.entity] 73bd631cc6ba05c96f7aec7ec67a2177 (Foo): Adding entity text.foo_code_slot_3_name
2024-03-22 06:09:49.366 DEBUG (MainThread) [custom_components.lock_code_manager.entity] 73bd631cc6ba05c96f7aec7ec67a2177 (Foo): Adding entity text.foo_code_slot_3_pin
2024-03-22 06:09:49.366 DEBUG (MainThread) [custom_components.lock_code_manager.entity] 73bd631cc6ba05c96f7aec7ec67a2177 (Foo): Adding entity switch.foo_code_slot_3_enabled
2024-03-22 06:09:49.366 DEBUG (MainThread) [custom_components.lock_code_manager.entity] 73bd631cc6ba05c96f7aec7ec67a2177 (Foo): Sending signal from switch.foo_code_slot_3_enabled to binary sensor that slot 3 is ready
2024-03-22 06:09:49.366 DEBUG (MainThread) [custom_components.lock_code_manager] 73bd631cc6ba05c96f7aec7ec67a2177 (Foo): Adding enabled entity for slot 3
2024-03-22 06:09:49.366 DEBUG (MainThread) [custom_components.lock_code_manager] 73bd631cc6ba05c96f7aec7ec67a2177 (Foo): Adding name entity for slot 3
2024-03-22 06:09:49.366 DEBUG (MainThread) [custom_components.lock_code_manager] 73bd631cc6ba05c96f7aec7ec67a2177 (Foo): Adding pin entity for slot 3
2024-03-22 06:09:49.366 DEBUG (MainThread) [custom_components.lock_code_manager] 73bd631cc6ba05c96f7aec7ec67a2177 (Foo): Adding pin_used entity for slot 3
2024-03-22 06:09:49.366 INFO (MainThread) [custom_components.lock_code_manager] 73bd631cc6ba05c96f7aec7ec67a2177 (Foo): Done creating and/or updating entities
2024-03-22 06:09:49.394 DEBUG (MainThread) [custom_components.lock_code_manager.coordinator] Finished fetching lock_code_manager lock.test_lock data in 0.000 seconds (success: True)
2024-03-22 06:09:49.397 DEBUG (MainThread) [custom_components.lock_code_manager.binary_sensor] 73bd631cc6ba05c96f7aec7ec67a2177 (Foo): Updating binary_sensor.foo_code_slot_1_active
2024-03-22 06:09:49.397 DEBUG (MainThread) [custom_components.lock_code_manager.binary_sensor] 73bd631cc6ba05c96f7aec7ec67a2177 (Foo): Updating binary_sensor.foo_code_slot_2_active
2024-03-22 06:09:49.398 DEBUG (MainThread) [custom_components.lock_code_manager.binary_sensor] 73bd631cc6ba05c96f7aec7ec67a2177 (Foo): Updating binary_sensor.foo_code_slot_3_active
2024-03-22 06:09:49.416 DEBUG (MainThread) [custom_components.lock_code_manager.entity] 73bd631cc6ba05c96f7aec7ec67a2177 (Foo): Adding entity binary_sensor.test_lock_code_slot_1_in_sync
```

**Comment by tykeal** [comment]
I then see a few more updates after I captured that with the following:

```
2024-03-22 06:10:49.148 DEBUG (MainThread) [custom_components.lock_code_manager.binary_sensor] 73bd631cc6ba05c96f7aec7ec67a2177 (Foo): Updating binary_sensor.foo_code_slot_2_active
2024-03-22 06:10:49.152 DEBUG (MainThread) [custom_components.lock_code_manager.binary_sensor] 73bd631cc6ba05c96f7aec7ec67a2177 (Foo): Updating binary_sensor.foo_code_slot_3_active
2024-03-22 06:10:49.158 DEBUG (MainThread) [custom_components.lock_code_manager.coordinator] Finished fetching lock_code_manager lock.test_lock data in 0.001 seconds (success: True)
2024-03-22 06:11:49.158 DEBUG (MainThread) [custom_components.lock_code_manager.coordinator] Finished fetching lock_code_manager lock.test_lock data in 0.001 seconds (success: True)
```

Which looks pretty standard but the entities all remain unavailable to me.

**Comment by tykeal** [comment]
:-/ ok, looks like my zwave lock is showing up as unavailable in HA for some reason even though ZWave-JS is showing it as active. So that will probably explain my unavailable entities. Let me figure out my test bed problem

**Comment by tykeal** [comment]
Right.... that's great. I knew this lock was having issues which is why I removed it from active service. Now the Zwave has gone flaky on me :laughing: I've got a spare lock for use on my properties if one of the locks fails suddenly. I guess I'll hook that up to my test instance.

**Comment by tykeal** [comment]
Given what I'm seeing I believe this will fix #98

**Pull request merged**
