### PR TITLE
Add support for virtual locks

### PR DESCRIPTION
**Pull request by raman325**
## Proposed change

Adds support for the `virtual` integration (https://github.com/twrecked/hass-virtual)

## Type of change

-   [ ] Dependency upgrade
-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [x] New feature (which adds functionality)
-   [ ] Breaking change (fix/feature causing existing functionality to break)
-   [ ] Code quality improvements to existing code or addition of tests

## Additional information

-   This PR fixes or closes issue: fixes https://github.com/raman325/lock_code_manager/issues/18
-   This PR is related to issue:

### CODE REVIEW

**Comment by tykeal** [comment]
@raman325 I got a chance to try this this morning.

I created a new LCM against a virtual lock I already had and got the following error in my logs after completing the setup:

```
2024-03-27 08:14:24.224 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/lock_code_manager/__init__.py", line 389, in async_update_listener
    ][CONF_LOCKS][lock_entity_id] = async_create_lock_instance(
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/lock_code_manager/helpers.py", line 32, in async_create_lock_instance
    assert lock_config_entry
AssertionError
```

I still have my (non-functional) Zwave lock setup with slots 1 - 3 configured.

I setup my new LCM based virtual lock with exactly the same parameters (just a different name).

So configuration was basically:

3 slots starting at 1.

Slot 1 configuration:
Name: Slot 1
Code: 0101
Enabled

Slot 2 configuration:
Name: RC live test
Code: 0202
Calendar: calendar.rental_control_live_test

Slot 3 configuration:
Name: RC Manual test
Code: 0303
Calendar: calendar.rental_control_manual_test

**Comment by raman325** [comment]
thanks, I assumed that you would have a config entry given the docs for the virtual integration but maybe there was an incorrect assumption there

**Comment by tykeal** [comment]
Virtual devices are created via YAML. That's all I know. I have the following in my configuration for my test system:

configuration.yaml:
```yaml
# just showing the bits that are relevant
lock: !include locks.yaml

# Enable virtual components platform
virtual:
```

locks.yaml
```yaml
- platform: virtual
  name: Test lock
```

This gives me a virtual lock that I can see in the LCM picker during configuration.

**Comment by tykeal** [comment]
:-/ weird, I updated updated my locks.yaml configuration to have a different name. Restarted, cleaned up the orphaned lock entity and no longer have a device related to the virtual lock, so it is no longer pickable in LCM. I'll debug that issue since I know you're looking for a device and not an entity. I'm not certain why it disappeared on me!

**Comment by tykeal** [comment]
Ok, I don't know what's going on now :cry: I went and looked at the Virtual Components integration. I was using the latest release v0.8.0.1 and saw that there was an alpha version that might fix some issues. I switched to that, I get a device related to the virtual lock. The virtual _also_ doesn't put `virtual_` in the entity name anymore it just looks like a lock just with an interesting attribute (`Persistent`). In any case, it still doesn't show up in the pick list for some reason now after my having gone and fiddled with the name.

**Comment by raman325** [comment]
the name shouldn't matter. Check `config/.storage/core.entity_registry` and look up your lock. Does it say `virtual` for the platform?

**Comment by tykeal** [comment]
@raman325 just updated to 2023.4.0 on my test system and the new virtual lock bits started working!

**Comment by raman325** [comment]
so is this good to merge?

**Pull request merged**
