### PR TITLE
CI: Setup pre-commit and related cleanup

### PR DESCRIPTION
**Pull request by tykeal**
- Refactor: Code cleanup via pre-commit hooks
- Refactor: Cleanup yamllint problems
- Refactor: Cleanup errors raised by actionlint
- CI: Add pre-commit validation and configuration

### CODE REVIEW

**Comment by tykeal** [comment]
@raman325 I noticed just after I finished my initial work on this that you are setting up pre-commit in your open test PR. My feelings are going to be hurt if you close this in favor of that ;)

As an FYI there's a couple of things I noticed looking over your code:

* You're stating that the minimum Python needed is 3.10 but requiring HA 2024.2 which requires Python 3.12
* You're importing future annotations which is not needed in Python 3.12

Also, I don't have mypy currently enabled in the pre-commit I'm raising here, but it raises 37 errors in the code base, basically all of which are related to improper annotation use or setting things against what the annotations state are acceptable

I did not enable prettier but I would strongly recommend it, it will, however, modify nearly all of the files in the repo

**Comment by raman325** [comment]
thanks for the contribution and for the comments! I have ported some of this over from keymaster and I'm slowly cleaning things up as I go but I definitely won't catch everything so additional eyes is helpful. I am going to merge this and then rebase my PR on this one.

**Comment by tykeal** [comment]
Since you merged this, I would recommend setting up [pre-commit ci](https://pre-commit.ci/) on the repo. It will trigger pre-commit validation runs on PRs

**Comment by raman325** [comment]
> * You're stating that the minimum Python needed is 3.10 but requiring HA 2024.2 which requires Python 3.12

btw this isn't the case yet: https://github.com/home-assistant/core/blob/dev/homeassistant/const.py#L22-L25

**Comment by tykeal** [comment]
Hmm... I guess I misread the announcement when they moved HAOS to 3.12

**Pull request merged**
